### ISSUE TITLE
"Loading dependency graph, done."

### ISSUE THREAD

**Issue by maximechbt** [FormidableLabs/appr#12]
Hello,
I have followed the documentation to configure appr but the build travis stops with the following error message:"Loading dependency graph, done.".

What could this problem be? I think it's because expo is launching the application and waiting for interactions, but I don't know how to fix this problem.

Thank you

**Comment by jevakallio** [comment]
@sofaws this was due to `exp` now requiring a `--non-interactive` flag, which was not set by Appr until I just merged https://github.com/FormidableLabs/appr/pull/11

I'm testing the latest versions now, and plan to release a new version shortly if everything checks out.

Edit: Version 1.1.0 is now published to NPM. Closing this issue, feel free to reopen if the issue continues with the newest version.
