### ISSUE TITLE
Pushing to Expo for master branch

### ISSUE THREAD

**Issue by cmwall** [FormidableLabs/appr#19]
I currently have a project set up to use appr by deploying pull requests (like the docs say).

Is there a way to deploy my master branch to the master Expo branch when master is updated?

Thanks!

**Comment by jevakallio** [comment]
This could definitely be done. All you'd really need to do is to NOT run the post-deploy script and leave out the ` "$CI_PULL_REQUEST" != ""` or ` "$TRAVIS_PULL_REQUEST" != ""` in the CI configuration.

Alternatively, you can run `exp login` and `exp publish` as CI steps post-build without appr, since that's what appr does internally.

**Comment by jevakallio** [comment]
We should investigate how we can support building non-PR branches. This would already work today, if we didn't make assumptions around having a PR to push comments to.
